name: aoc2023
version: 2023.0
github: "git@github.com:MarusDod/aoc2023.git"
license: BSD3
author: "Marcos Domingues"
maintainer: "markitos.2001@hotmail.com"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: My solutions for aoc 2023 in haskell

dependencies:
  - base
  - time
  - directory
  - containers
  - text
  - mtl
  - ansi-terminal
  - attoparsec
  - optparse-applicative
  - parser-combinators
  - vector

library:
  source-dirs: src
  default-extensions:
    - LambdaCase
    - MultiWayIf
    - RecordWildCards
    - OverloadedRecordDot
    - OverloadedStrings
    - GADTs
    - GHC2021

executables:
  aoc2023-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
      - -with-rtsopts=-qa
      - -with-rtsopts=-C0
      - -funfolding-use-threshold=16
      - -fexcess-precision
      - -optc-O3
      - -optc-ffast-math
      - -O2
    default-extensions:
      - LambdaCase
      - MultiWayIf
      - RecordWildCards
      - OverloadedRecordDot
      - OverloadedStrings
      - GADTs
      - GHC2021
    dependencies:
      - aoc2023
